name: Save Price History

on:
  workflow_dispatch:

  schedule:
    # 평일(월~금) 16:10 KST = 07:10 UTC
    - cron: "10 7 * * 1-5"

jobs:
  save-history:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Save History
        run: python3 csv_main.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DOMESTIC_STOCK_INFO_DB_ID: ${{ secrets.NOTION_DOMESTIC_STOCK_INFO_DB_ID }}
          NOTION_NET_PROFIT_DB_ID: ${{ secrets.NOTION_NET_PROFIT_DB_ID }}
